# Generated by Django 4.0.5 on 2022-06-25 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petfinder', '0003_profile_location_alter_post_image_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='active',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='friendly',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='health',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='house_trained',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='image_three',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='image_two',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='kids',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='org_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='bio',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='post',
            name='dog_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=150),
        ),
    ]
